django_project/django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('my_app.urls')),
]

django_project/my_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
	path('', views.index, name='index'),
	path('publications/', views.publications, name='publications'),
	path('research/', views.research, name='research'),	
	path('code/', views.code, name='code'),
	path('contact/', views.contact, name='contact'),
	path('registration/', views.registration, name='registration'),
	path('activate/', views.activate, name='activate'), 
]

django_project/my_app/models.py
from django.db import models
from django.utils import timezone 
from django.core.validators import validate_email

# First create the class
    # add __str__ to the class (will be shown the contenct in the admin panel)
# Add the class to admin.py to allow manage the content in the admin panel 
# Run makemigration for the app
# Run migrate
# Check admin panel

 
class Comment(models.Model):
    name = models.CharField(max_length=30)
    email = models.EmailField(blank=False, validators=[validate_email], default='null')
    comment = models.TextField()
    url_name = models.TextField()
    date_added = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return '<Name: {}, ID: {}, URL_name: {}>'.format(self.name, self.id, self.url_name)


class TemporaryUser(models.Model):
    username = models.CharField(max_length=30)
    email = models.EmailField(blank=False, validators=[validate_email], default='null')
    password = models.CharField(max_length=64)
    date_added = models.DateTimeField(default=timezone.now)
    activation_code = models.TextField(blank=False, default='null')
    
    def __str__(self):
        return '<Name: {}, ID: {}, Email: {}>'.format(self.username, self.id, self.email)
    
class User(models.Model):
    username = models.CharField(max_length=30)
    email = models.EmailField(blank=False, validators=[validate_email], default='null')
    password = models.CharField(max_length=64)
    date_added = models.DateTimeField(default=timezone.now)
    
    def __str__(self):
        return '<Name: {}, ID: {}, Email: {}>'.format(self.username, self.id, self.email)

django_project/my_app/forms.py
# A class that represents the form in a HTML file
from django import forms


class CommentForm(forms.Form):
    atrb_name = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Name' }))
    atrb_email = forms.EmailField(max_length=30,
                                widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Email' }))
    atrb_comment = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Comment', 'style' : 'resize: none;' }))

    
class TemporaryUserForm(forms.Form):
    atrb_username = forms.CharField(max_length=30,
                                widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Username' }))
    atrb_email = forms.EmailField(max_length=30,
                                widget=forms.TextInput(attrs={'class' : 'form-control', 'placeholder' : 'Email' }))
    atrb_password = forms.CharField(widget=forms.Textarea(attrs={'class' : 'form-control', 'placeholder' : 'Password' }))
    

django_project/my_app/views.py
from .models import Comment
from .models import TemporaryUser

from .forms import CommentForm
from .forms import TemporaryUserForm

from django.http.response import HttpResponse 
from django.urls.base import resolve
from django.shortcuts import render 

from _sha256 import sha256
import uuid 


def index (request):
    current_url = 'home';
    current_path = 'home'; 
    context = {'page_name' : current_url, 'current_path' : current_path}
    return render(request, 'webcontext/index.html', context)


def publications (request): 
    current_url = resolve(request.path_info).url_name;
    current_path = request.get_full_path();
    if request.method == 'POST':  
        new_comment = Comment(name=request.POST['atrb_name'], email=request.POST['atrb_email'], comment=request.POST['atrb_comment'], url_name=current_url)
        new_comment.save()
        return HttpResponse('')
    else:
        form = CommentForm()
 
    comments = Comment.objects.filter(url_name=current_url).order_by('-date_added')
    print('The URL name: ' + current_url);
    context = {'comments' : comments, 'form' : form, 'page_name' : current_url, 'current_path' : current_path}
    return render(request, 'webcontext/publications.html', context)   


def research (request): 
    current_url = resolve(request.path_info).url_name;
    current_path = request.get_full_path();
    context = {'page_name' : current_url, 'current_path' : current_path}
    return render(request, 'webcontext/research.html', context)   


def contact (request): 
    current_url = resolve(request.path_info).url_name;
    current_path = request.get_full_path();
    if request.method == 'POST':  
        # form = CommentForm(request.POST)
        # if form.is_valid():
        #    new_comment = Comment(name=request.POST['atrb_name'],  email=request.POST['atrb_email'], comment=request.POST['atrb_comment'])
        #    new_comment.save()
        #    return redirect('comment') 
        new_comment = Comment(name=request.POST['atrb_name'], email=request.POST['atrb_email'], comment=request.POST['atrb_comment'], url_name=current_url)
        new_comment.save()
        return HttpResponse('')
    else:
        form = CommentForm()

    # comments = Comment.objects.order_by('-date_added') 
    comments = Comment.objects.filter(url_name=current_url).order_by('-date_added')
    print('The URL name: ' + current_url);
    context = {'comments' : comments, 'form' : form, 'page_name' : current_url, 'current_path' : current_path}
    return render(request, 'webcontext/contact.html', context)   


def code (request): 
    current_url = resolve(request.path_info).url_name;
    current_path = request.get_full_path();
    if request.method == 'POST':  
        new_comment = Comment(name=request.POST['atrb_name'], email=request.POST['atrb_email'], comment=request.POST['atrb_comment'], url_name=current_url)
        new_comment.save()
        return HttpResponse('')
    else:
        form = CommentForm()
 
    comments = Comment.objects.filter(url_name=current_url).order_by('-date_added')
    print('The URL name: ' + current_url);
    context = {'comments' : comments, 'form' : form, 'page_name' : current_url, 'current_path' : current_path}
    return render(request, 'webcontext/code.html', context)   


def registration (request): 
    current_url = resolve(request.path_info).url_name;
    current_path = request.get_full_path();
    if request.method == 'POST':  
        print('Storing user ', request.POST['atrb_username'], '.')
        hashed_password = hash_password(request.POST['atrb_password'])
        temp_user = TemporaryUser(username=request.POST['atrb_username'], email=request.POST['atrb_email'], password=hashed_password, activation_code=uuid.uuid4())
        temp_user.save()
        send_email(temp_user.username, temp_user.email, str(temp_user.activation_code))
        return HttpResponse('')
    else:
        form = TemporaryUserForm()

    print('The URL name: ' + current_url);
    context = {'form' : form, 'page_name' : current_url, 'current_path' : current_path}
    return render(request, 'webcontext/registration.html', context)   


def activate (request): 
    current_url = resolve(request.path_info).url_name;
    current_path = request.get_full_path();
    username = 'Null' 
    if request.method == 'GET':  
        parameter_code = request.GET.get('code','')
        print('the code parameter',parameter_code)
        
        user_object = TemporaryUser.objects.get(activation_code=parameter_code)
        username = user_object.username
        # get user name from parameter and load username from database
    
    context = {'username' : username, 'page_name' : current_url, 'current_path' : current_path}
    return render(request, 'webcontext/activate.html', context)   


def hash_password(password):
    hex_dig = sha256(password.encode('ascii')).hexdigest()
    return hex_dig
 
        
def send_email(username, recipient, activation_code):
    import smtplib
    
    from email.mime.multipart import MIMEMultipart
    from email.mime.text import MIMEText
    
    # sender == my email address 
    sender = 'wtl4ever@gmail.com' 
    pwd = '!Ww33423554'
    
    # Create message container - the correct MIME type is multipart/alternative.
    msg = MIMEMultipart('alternative')
    msg['Subject'] = "Activate your account"
    msg['From'] = sender
    msg['To'] = recipient
    
    # Create the body of the message (a plain-text and an HTML version).
    text = "Dear" + username + "\nYou are almost done!\nPlease click in the link to activate your account: http://localhost:8000/activate?code=" + activation_code
    html = """\
    <html>
      <head></head>
      <body>
        <p>You are almost done!<br>
           Click <a href="http://localhost:8000/activate?code=""" + activation_code + """\">here</a> or in the link below to activate your account.<br>
           http://localhost:8000/activate?code=""" + activation_code + """\
        </p>
      </body>
    </html>
    """
    
    # Record the MIME types of both parts - text/plain and text/html.
    part1 = MIMEText(text, 'plain')
    part2 = MIMEText(html, 'html')
    
    # Attach parts into message container.
    # According to RFC 2046, the last part of a multipart message, in this case
    # the HTML message, is best and preferred.
    msg.attach(part1)
    msg.attach(part2)
    # Send the message via local SMTP server.
    mail = smtplib.SMTP('smtp.gmail.com', 587)
    
    mail.ehlo()
    
    mail.starttls()
    
    mail.login(sender, pwd)
    mail.sendmail(sender, recipient, msg.as_string())
    mail.quit()

django_project/my_app/templates/webcontext/activate.html
{% load static %} {% load custom_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Willian Tessaro Lunardi" />
<meta name="description" content="Personal webpage of Willian Tessaro Lunardi" />
<meta name="keywords" content="optimization,combinatorial,student,university,luxembourg,website,graduate,willian tessaro lunardi," />

<title>{% get_page_title %}</title>

<link rel="shortcut icon" type="image/png" href="{% static 'webcontext/images/favicon.png' %}" />
<link href="{% static 'webcontext/css/boot4/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'webcontext/css/style.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
	{% include "webcontext/html_parts/nav.html" %}

	<section class="py-5 container" id="contact">
		<div class="row">
			<div class="col-lg-8 mx-auto text-center">
				<h2 class="section-heading">Congratulations</h2>
				<hr style="max-width: 50px; border-width: 3px; border-color: #f05f40;" class="my-4">
				<p class="mb-5">
					Your account <i>{{ username }}</i> is now validated! 
				</p>
			</div>
		</div> 
	</section>

	{% include "webcontext/html_parts/footer_short_content.html" %}

	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<!-- <script
		src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script> -->
	<script src="{% static 'webcontext/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webcontext/js/form_comment.js' %}"></script> 
</body>
</html>

django_project/my_app/templates/webcontext/code.html
{% load static %} {% load custom_tags %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Willian Tessaro Lunardi" />
<meta name="description"
	content="Personal webpage of Willian Tessaro Lunardi" />
<meta name="keywords"
	content="optimization,combinatorial,student,university,luxembourg,website,graduate,willian tessaro lunardi," />

<title>{% get_page_title %}</title>

<link rel="shortcut icon" type="image/png"
	href="{% static 'webcontext/images/favicon.png' %}" />
<link href="{% static 'webcontext/css/boot4/bootstrap.css' %}"
	rel="stylesheet">
<link href="{% static 'webcontext/css/style.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
	{% include "webcontext/html_parts/nav.html" %}

	<div class="container py-5" id="content_section" role="main">
		<div class="text-center">
			<img class="d-block mx-auto mb-4"
				src="{% static 'webcontext/images/logo_0.png' %}" alt="" width="96"
				height="96">
			<h2 style="margin-top: 0px;">
				Check my <a target="_blank" href="https://github.com/Willtl">Github</a>
			</h2>
			<hr
				style="max-width: 50px; border-width: 3px; border-color: #f05f40;"
				class="my-4">
			<p class="lead">Below is an example form built entirely with
				Bootstrap's form controls. Each required form group has a validation
				state that can be triggered by attempting to submit the form without
				completing it.</p>
		</div>

		<div class="row py-5">
			<div class="col">
				<div class="card">
					<div class='card-img-top container gfyitem'
						data-id='DampFlickeringCirriped'></div>
					<div class="card-body">
						<h5 class="card-title">Card title</h5>
						<p class="card-text">Some quick example text to build on the
							card title and make up the bulk of the card's content.</p>
						<a href="#" class="btn btn-primary btn-outline-primary">Go somewhere</a>
					</div>
				</div>
			</div>
			<div class="col">
				<div class="card">
					<div class='card-img-top container gfyitem'
						data-id='DampFlickeringCirriped'></div>
					<div class="card-body">
						<h5 class="card-title">Card title</h5>
						<p class="card-text">Some quick example text to build on the
							card title and make up the bulk of the card's content.</p>
						<a href="#" class="btn btn-primary btn-outline-primary">Go somewhere</a>
					</div>
				</div>
			</div>
		</div>
		<div class="row py-5">
			<div class="col">
				<div class='gfyitem' data-id=CheapRegalConch></div>
			</div>
		</div>
		{% include "webcontext/html_parts/comment_area.html" %}
	</div>

	<div class="container" style="position: relative;">
		<input id="page_id" type="hidden" value="{{ current_path }}">
		{% include "webcontext/html_parts/comment_form.html" %}
	</div>
	{% include "webcontext/html_parts/footer.html" %}

	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<!-- <script
		src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script> -->
	<script src="{% static 'webcontext/js/bootstrap.min.js' %}"></script>
	<script src='https://www.google.com/recaptcha/api.js'></script>
	<script src="{% static 'webcontext/js/form_comment.js' %}"></script>
	<script>
		(function(d, s, id) {
			var js, fjs = d.getElementsByTagName(s)[0];
			if (d.getElementById(id)) {
				return;
			}
			js = d.createElement(s);
			js.id = id;
			js.src = "https://assets.gfycat.com/gfycat.js";
			fjs.parentNode.insertBefore(js, fjs);
		}(document, 'script', 'gfycat-js'));
	</script>
</body>
</html>

django_project/my_app/templates/webcontext/comment.html
{% load static %} {% load random_numbers %}

<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="favicon.ico">

<title>Theme Template for Bootstrap</title>

<!-- Bootstrap core CSS -->
<link href="{% static 'webcontext/css/bootstrap.min.css' %}"
	rel="stylesheet">
<link href="{% static 'webcontext/css/style.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
	<!-- Fixed navbar -->
	<div class="container">
		<nav class="navbar navbar-default navbar-expand-sm navbar-light"
			role="navigation">
			<div class="container">
				<div class="navbar-header">
					<button type="button" class="navbar-toggle collapsed"
						data-toggle="collapse" data-target="#navbar" aria-expanded="false"
						aria-controls="navbar">
						<span class="sr-only">Toggle navigation</span> <span
							class="icon-bar"></span> <span class="icon-bar"></span> <span
							class="icon-bar"></span>
					</button>
					<a class="navbar-brand" href="{% url 'index' %}">Willian
						Tessaro Lunardi</a>
				</div>
				<div id="navbar" class="navbar-collapse collapse">
					<ul class="nav navbar-nav">
						<li class=nav-item><a class="nav-link"
							href="{% url 'index' %}">Home</a></li>
						<li class=nav-item><a class="nav-link"
							href="{% url 'comment_1' %}">Comments</a></li>
						<li class=nav-item><a class="nav-link" href="#contact">Contact</a></li>
					</ul>
				</div>
				<!--/.nav-collapse -->
			</div>
		</nav>
	</div>

	<div id="content_section" class="container">
		<div id="post_section" class="jumbotron">
			<h1>Theme example</h1>
			<p>This is a template showcasing the optional theme stylesheet
				included in Bootstrap. Use it as a starting point to create
				something more unique by building on or modifying it.</p>
		</div>

		<div id="comment_section" class="row">
			{% if comments %}
			<div id="comments_header" class="page-header">
				<h1>Comments</h1>
			</div>
			{% for c in comments %}
			<div class="panel panel-white post panel-shadow">
				<div class="post-heading">
					<div class="pull-left image">
						<img
							src="{% static 'webcontext/images/avatar/avatar' %}-{% random_int 1 6 %}.png"
							class="img-circle avatar">
					</div>
					<div class="pull-left meta">
						<div class="title h5">
							<a href="#"><b>{{ c.name }}</b></a> made a post.
						</div>
						<h6 class="text-muted time">{{ c.date_added }}</h6>
					</div>
				</div>
				<div class="post-description ">
					<p id="comment_area">{{ c.comment }}</p>
				</div>
			</div>
			{% endfor %} {% endif %}
		</div>
	</div>

	<div class="container">
		<div id="form_comment" class="row">
			<div class="page-header">
				<h1>Add Comments</h1>
			</div>
			<form id="comment_form" method="POST">
				<div id="comment_form_error" class="alert alert-danger" role="alert"
					style="display: none;">
					<span class="glyphicon glyphicon-exclamation-sign"
						aria-hidden="true"></span> <span id="error_message"></span>
				</div>
				<div id="comment_form_info" class="alert alert-warning" role="alert"
					style="display: none;">
					<span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
					<span id="info_message"></span>
				</div>
				<input id="id_csrf_token" type='hidden' name='csrfmiddlewaretoken'
					value='{{ csrf_token }}' />
				<div class="form-group">
					<input name="atrb_name" class="form-control" placeholder="Name"
						maxlength="30" id="id_atrb_name" type="text" required>
				</div>
				<div class="form-group">
					<input name="atrb_email" class="form-control" placeholder="Email"
						maxlength="30" id="id_atrb_email" type="text" required>
				</div>
				<div class="form-group">
					<textarea name="atrb_comment" cols="40" rows="10"
						class="form-control" placeholder="Comment" style="resize: none;"
						id="id_atrb_comment" required></textarea>
				</div>
				<button id="button_comment_form"
					class="btn btn-lg btn-primary btn-block" type="submit">Submit</button>
			</form>
		</div>

		<div class="page-header">
			<h1>Wells</h1>
		</div>
		<div class="well">
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit.
				Maecenas sed diam eget risus varius blandit sit amet non magna.
				Lorem ipsum dolor sit amet, consectetur adipiscing elit. Praesent
				commodo cursus magna, vel scelerisque nisl consectetur et. Cras
				mattis consectetur purus sit amet fermentum. Duis mollis, est non
				commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem
				nec elit. Aenean lacinia bibendum nulla sed consectetur.</p>
		</div>

		<input id="page_id" type="hidden" value="{% url 'comment_1' %}">
	</div>
	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script
		src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<script src='https://www.google.com/recaptcha/api.js'></script>
	<script src="{% static 'webcontext/js/bootstrap.min.js' %}"></script>
	<script src="{% static 'webcontext/js/form_comment.js' %}"></script>
</body>
</html>

django_project/my_app/templates/webcontext/registration.html
{% load static %} {% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">

<meta name="author" content="Willian Tessaro Lunardi" />
<meta name="description" content="Personal webpage of Willian Tessaro Lunardi" />
<meta name="keywords" content="optimization,combinatorial,student,university,luxembourg,website,graduate,willian tessaro lunardi," />

<title>{% get_page_title %}</title>

<link rel="shortcut icon" type="image/png" href="{% static 'webcontext/images/favicon.png' %}" />
<link href="{% static 'webcontext/css/boot4/bootstrap.css' %}" rel="stylesheet">
<link href="{% static 'webcontext/css/style.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>

<body>
	{% include "webcontext/html_parts/nav.html" %}

	<div class="container" style="position: relative;">
		<input id="page_id" type="hidden" value="{{ current_path }}">

		<div class="container py-5" id="content_section" role="main">
			<div class="text-center">
				<h2 style="margin-top: 0px;">Registration</h2>
				<hr style="max-width: 50px; border-width: 3px; border-color: #f05f40;" class="my-4">
			</div>
			<div class="main-login main-center">
				<form id="register_form" method="POST">
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon1">
								<i class="far fa-user"></i>
							</span>
						</div>
						<input id="id_atrb_username" type="text" style="width: 80%" class="form-control" placeholder="Username" aria-label="Username" aria-describedby="basic-addon1">
						<small class="text-muted">This will be your username.</small>
					</div>
					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon1">
								<i class="far fa-envelope"></i>
							</span>
						</div>
						<input id="id_atrb_email" type="email" style="width: 80%" class="form-control" placeholder="Email" aria-label="Email" aria-describedby="basic-addon1">
						<small class="text-muted">We'll occasionally send updates about your account to this inbox. We'll never share your email address with anyone.</small>
					</div>

					<div class="input-group mb-3">
						<div class="input-group-prepend">
							<span class="input-group-text" id="basic-addon1">
								<i class="far fa-eye-slash"></i>
							</span>
						</div>
						<input id="id_atrb_password" type="password" style="width: 80%" class="form-control" placeholder="Password" aria-describedby="basic-addon1">
						<small class="text-muted">Use at least one lowercase letter, one numeral, and seven characters.</small>
					</div>
					<input id="id_csrf_token" type='hidden' name='csrfmiddlewaretoken' value='{{ csrf_token }}' />
					<button id="button_register" type="submit" class="btn btn-primary btn-lg btn-block login-button btn-outline-primary">Register</button>
				</form>
			</div>
		</div>
	</div>

	{% include "webcontext/html_parts/footer_short_content.html" %}

	<!-- Bootstrap core JavaScript
    ================================================== -->
	<!-- Placed at the end of the document so the pages load faster -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
	<!-- <script
		src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script> -->
	<script src='https://www.google.com/recaptcha/api.js'></script>
	<script src="{% static 'webcontext/js/registration.js' %}"></script>
</body>
</html>